//LOCALHOST
### Get all temples
GET http://localhost:3000/temples

### Get  temple by id
GET http://localhost:3000/temples/687a875d3a3fcbf0fa6ceca7

### Create temple

POST http://localhost:3000/temples  HTTP/1.1
content-type: application/json

{
    
    "templeName": "Aba",
    "country": "Nigeria",
    "email" : "nigeriatemple@gmail.com",
    "dateDedication": "7 August 2005",
    "phone": "+234 0803 903 4810"
    
    

}

### PUT temple
PUT http://localhost:3000/temples/687a89043a3fcbf0fa6ceca9 HTTP/1.1
content-type: application/json

{
  "templeName": "Aba",
  "country": "Nigeria",
  "email" : "nigeriatemple@gmail.com",
  "dateDedication": "7 August 2005",
  "phone": "+234 0803 903 480"
}

### DELETE temple
DELETE http://localhost:3000/temples/687a89043a3fcbf0fa6ceca9"  HTTP/1.1




### Get all places
GET http://localhost:3000/places

### Get  place by id
GET http://localhost:3000/places/6887e16660016b44d1fbd410

### Create place

POST http://localhost:3000/places  HTTP/1.1
content-type: application/json

{
    
    "namePlace": "Altar",
    "altitude": "2.234.m.s.m",
    "email" :"altarplace@gmail.com",
    "phone": "+ (23)4556677",
    "sport": "Climbing"
}

### PUT temple
PUT http://localhost:3000/places/6887e1ff60016b44d1fbd411 HTTP/1.1
content-type: application/json

{
  "namePlace": "Altar",
  "altitude": "2.234.m.s.m",
  "email" :"altarplace@gmail.com",
  "phone": "+ (23)4556677",
  "sport": "Climbing"
}

### DELETE place
DELETE http://localhost:3000/places/6887e1ff60016b44d1fbd411"  HTTP/1.1



